#!/bin/sh

if [[ $1 == upgrade ]]; then
    /usr/bin/launchctl unload /Library/LaunchDaemons/com.1conan.cumsync.plist
    /usr/bin/launchctl load /Library/LaunchDaemons/com.1conan.cumsync.plist
fi

if [[ $1 == install ]]; then
    /usr/bin/launchctl load -w /Library/LaunchDaemons/com.1conan.cumsync.plist
fi

exit 0
